### ISSUE TITLE
suggest appfilter/

### ISSUE THREAD

**Issue by Kexagia** [afollestad/polar-dashboard#123]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Polar Dashboard.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `0.8.5.8`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

Please wrap logs with Gradle syntax highlighting (it makes them look better):

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.afollestad.polar.ui.HelloWorld
    at com.afollestad.polar.ui.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kava)
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by Kexagia** [comment]
Do you suggest me a appfilter.xml source?

**Comment by danielhickman** [comment]
If I understand you correctly, in that you're looking for how you can get the activities to put in your appfilter, then there's a few options.

**Here's one that's been out there for a long time so some activities have changed since:**
https://github.com/a-random-package/AppFilter/blob/master/appfilter.xml

**If you have the apps you want to theme installed and you have Nova Launcher installed:**
1. Open `Nova Settings`
2. Hold the volume down button to enable `Labs`
3. Scroll down to the bottom and tap `Debug`
4. Tap `Export Icons for theme dev` and wait for it to finish
5. You can find the appfilter in the ZIP file it created

**You can use activity finder apps as well:**
https://play.google.com/store/apps/details?id=com.cleanapps.packagemanager

**Nova also has an activity helper in Labs:**
1. Open `Nova Settings`
2. Hold the volume down button to enable `Labs`
3. Scroll down to the bottom and tap `Debug`
4. Enable `Show Component in Edit dialog`
5. Now you can edit an app from the launcher revealing it's activity below it's name (Hint: long press to copy to clipboard)

**Comment by Kexagia** [comment]
thanks :) so

2016-06-18 21:27 GMT+03:00 Daniel Hickman <notifications@github.com>:
