### ISSUE TITLE
Implement time-sensitive request limits

### ISSUE THREAD

**Issue by TWellington** [afollestad/polar-dashboard#75]
This way, users could only request fifteen icons in a given time period. Say, fifteen a month, year, millennium, etc.

**Comment by afollestad** [comment]
Good idea, I'll try to work on this when I get home later

**Comment by jahirfiquitiva** [comment]
Hi

I'm here to kindly ask you not to do this.

Why? Because I have implemented in IconShowcase and it's basically losing all its unique features.

I know you consider this a competition but can you still leave some "space" or "room" for IconShowcase?

This has happened already with the LG Home Support which I explained to Kevin and the appfilter warnings/errors shown in log.

I hope you understand and consider it. Thanks.

**Comment by afollestad** [comment]
Nothing of what I have done has been related to  or modelled off of IconShowcase.

I'm implementing requested features or things I think would be useful to my many users.

**Comment by jahirfiquitiva** [comment]
I didn't say you were taking code from IconShowcase, Aidan.

And I know you're just implementing what people ask you but basically many of them were asking something I already implemented on IconShowcase and they knew it because I was posting all the progress in the community, and since you released Polar faster than I released IconShowcase, they instantly came here just to request what I had already done.

Aidan, I respect and admire you, but really all these things are making me hopeless on my own works and efforts.

I was simply requesting you not to do it, but is your decision at the end.
