### ISSUE TITLE
IAP's for things

### ISSUE THREAD

**Issue by Beasto** [afollestad/polar-dashboard#87]
I just wanted to be able to have a free app but have IAP's that make it unlock things like more icons or widgets or things like that.

Thanks!

**Comment by Blezensky** [comment]
IAP for premium request will be nice. Like $5 for x icons.

**Comment by danielhickman** [comment]
I don't believe you can add more icons or widgets since you can't change XML values, drawables, or assets post install. You could probably do it with wallpapers, but it would be silly since the URL found be found and the image are public.

I do however like the idea of paid requests. https://github.com/afollestad/polar-dashboard/issues/15#issuecomment-196299988

**Comment by TWellington** [comment]
Paid requests are just a money grab for icon pack creators, and I feel it's
overused. There are dashboards that already let you do this.

**Comment by danielhickman** [comment]
True, but it still seems to be a win-win.

**Comment by TWellington** [comment]
I don't think it is at all. Users are taken advantage of for a service that
should be included with any app that allows you to send requests.
